language: python
python:
  - "3.6"
# command to install dependencies
before_install:
  - pip install pipenv
  - pipenv lock --requirements > requirements.txt
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest pytest-cov
  - pip install pep8
# command to run tests
script:
  - pytest --cov=./
after_success:
  - codecov